@DemoApi_HostAddress = http://localhost:5000

### Process id
GET http://localhost:5000/api/demo/pid

### Fast endpoint
GET {{DemoApi_HostAddress}}/api/demo/fast
Accept: application/json

### Slow endpoint
GET {{DemoApi_HostAddress}}/api/demo/slow
Accept: application/json

### Memory leak endpoint
GET {{DemoApi_HostAddress}}/api/demo/leak
Accept: application/json

### CPU intensive endpoint
GET {{DemoApi_HostAddress}}/api/demo/cpu
Accept: application/json

### Get all messages (DB)
GET http://localhost:5000/api/demo/messages
Accept: application/json

### Insert a new message (DB)
POST http://localhost:5000/api/demo/messages
Content-Type: application/json

{
  "text": "Hello from .http file"
}

### This will eventually exhaust pool
GET http://localhost:5000/api/demo/db-leak

### Static endpoint that leaks DB connections
GET http://localhost:5000/api/demo/db-static

### Safe endpoint
GET http://localhost:5000/api/demo/db-ok

### Slow DB query
GET http://localhost:5000/api/demo/db-slow

### Cached DB query
GET http://localhost:5000/api/demo/db-cached